fix: Adjust config

diff --git a/.github/workflows/version-set.yml b/.github/workflows/version-set.yml
--- a/.github/workflows/version-set.yml
+++ b/.github/workflows/version-set.yml
@@ -13,13 +13,13 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
         with:
-          repository: 'geokrety/justatest'
           path: 'source'
 
       - name: Get values
         id: vars
         run: |
           echo GITHUB_REF_NAME: $GITHUB_REF_NAME
+          [ -f source/.versionset ] || { echo ".versionset file missing"; exit 1; }
           echo "version_set_name=$(cat source/.versionset)" >> $GITHUB_OUTPUT
 
       - name: Update Version-Set
